### PR TITLE
new method 'get_current_test_status'

### PR DESCRIPTION
**Pull request by tirolerstefan**
parses the (live) self test execution state from capability section.

### CODE REVIEW

**Comment by tirolerstefan** [comment]
Maybe useful.

I needed a stateless test execution status result. 
This is possible by parsing the "Self-test" lines in capabilites section,

**Comment by tirolerstefan** [comment]
Done, included into the intel test. 
I also added a new test file for my Samsung SSD.

By this, I changed the return code (shift right 4 bits) and created a separate method for querying the capabilities.

Another question - are you Marc?

**Comment by winkidney** [comment]
@tirolerstefan Thanks for you great job : )
Answer for another question: not Marc but winkidney, this will not stop us from being friends, LOL.

**Comment by tirolerstefan** [comment]
:-)
Just asking because I'm not sure whether this is the official pySMART repository. The creator is Marc Herndon, but I didn't find any pySMART repo of him nor could I find an email address to contact him where I can contribute.

**Comment by winkidney** [comment]
Yes, Marc himself has a explain in his code that we can contact to him directly.
It is a problem that no official repo provided for us, so I created one for who cares this project : )
This project is licensed as GPL v2, so I 'm sure that we can re-publish the source code here.

**Pull request merged**
