### PR TITLE
Split test for megaraid

### PR DESCRIPTION
**Pull request by volans-**
As requested in #2 this split the test for MegaRAID.

### CODE REVIEW

**Comment by winkidney** [comment]
thanks for you commit:)

**Comment by volans-** [comment]
@winkidney thanks for the quick review and merge.
Do you plan to make a new PyPI release in the near future?

**Comment by winkidney** [comment]
@volans- The problem is that we haven't the ownership of pysmart package on pypi. This is a fork, not the official package.
We have created a unofficial release named "pysmart.smartx" but only works for us : )

I haven't tried to connect with the original author yet. Maybe we can have a try.

Any idea?

**Comment by volans-** [comment]
@winkidney I was referring to the forked one: https://pypi.python.org/pypi/pySMART.smartx

But yes, in theory it would be good to merge all the efforts in a single package. I guess you could try to contact him using the email in setup.py.

**Comment by winkidney** [comment]
@volans- A bad news, test can not pass in my ubuntu-16 64bit, Error message listed below

```
py.test
================================================================================================================== test session starts ==================================================================================================================
platform linux2 -- Python 2.7.12, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: /home/winkidney/workspace/tools/pySMART, inifile: 
plugins: django-3.1.2, cov-2.4.0
collected 5 items 

pySMART/test/test_device_intel.py .
pySMART/test/test_device_samsung.py .
pySMART/test/test_device_seagate.py .
pySMART/test/test_macos.py F
pySMART/test/test_megaraid_controller.py .

======================================================================================================================= FAILURES ========================================================================================================================
_____________________________________________________________________________________________________________ TestDeviceOnMacOs.test_macos ______________________________________________________________________________________________________________

self = <pySMART.test.test_macos.TestDeviceOnMacOs instance at 0x7f237407fab8>
macos_cmd_all = ('\nsmartctl 6.5 2016-05-07 r4318 [Darwin 16.4.0 x86_64] (local build)\nCopyright (C) 2002-16, Bruce Allen, Christian ...read-scan remainder of disk.\nIf Selective self-test is pending on power-up, resume after 0 minute delay.\n\n    ', '')
macos_cmd_scan_open_as_root = ('\nIOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP06@1C,5/IOPP/SSD0@0/AppleAHCI/PRT0@0/IOAHCIDevice@0/Apple...6@1C,5/IOPP/SSD0@0/AppleAHCI/PRT0@0/IOAHCIDevice@0/AppleAHCIDiskDriver/IOAHCIBlockStorageDevice, ATA device\n    ', '')
macos_cmd_capabilities = ('\nsmartctl 6.5 2016-05-07 r4318 [Darwin 16.4.0 x86_64] (local build)\nCopyright (C) 2002-16, Bruce Allen, Christian ...lling time: \t (   2) minutes.\nExtended self-test routine\nrecommended polling time: \t (  10) minutes.\n\n     ', '')

    def test_macos(
        self,
        macos_cmd_all,
        macos_cmd_scan_open_as_root,
        macos_cmd_capabilities,
    ):
        """
            This test is to ensure that the parse can be executed without exception.
            """
        from pySMART.device import Device
        with nested(
            mock.patch.object(
                Device,
                "_cmd_all_with_type",
            ),
            mock.patch.object(
                Device,
                "_cmd_scan_open",
            ),
            mock.patch.object(
                Device,
                "_cmd_all",
            ),
            mock.patch.object(
                Device,
                "_cmd_get_capabilities",
            ),
        ) as (mocked_all_with_type, mocked_scan, mocked_all, mocked_cap):
            mocked_all_with_type.return_value = macos_cmd_all
            mocked_scan.return_value = macos_cmd_scan_open_as_root
            mocked_all.return_value = macos_cmd_all
            mocked_cap.return_value = macos_cmd_capabilities
>           device = Device("IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP06@1C,5/IOPP/SSD0@0/AppleAHCI/PRT0@0/IOAHCIDevice@0/AppleAHCIDiskDriver/IOAHCIBlockStorageDevice")

pySMART/test/test_macos.py:189: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pySMART/device.py:140: in __init__
    self._classify()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <ATA device on IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP06@1C,...0/IOAHCIDevice@0/AppleAHCIDiskDriver/IOAHCIBlockStorageDevice mod:None sn:None>

    def _classify(self):
        """
            Disambiguates generic device types ATA and SCSI into more specific
            ATA, SATA, SAS, SAT and SCSI.
            """
        # SCSI devices might be SCSI, SAS or SAT
        # ATA device might be ATA or SATA
        if self.interface in ['scsi', 'ata']:
            if self.interface == 'scsi':
                test = 'sat'
            else:
                test = 'sata'
            # Look for a SATA PHY to detect SAT and SATA
            _stdout, _stderr = self._cmd_sataphy(test)
>           if 'GP Log 0x11' in _stdout.split('\n')[3]:
E           IndexError: list index out of range

pySMART/device.py:208: IndexError
================================================================================================================ pytest-warning summary =================================================================================================================
WC1 /home/winkidney/workspace/tools/pySMART/pySMART/test_entry.py cannot collect test class 'Test_Entry' because it has a __init__ constructor
================================================================================================= 1 failed, 4 passed, 1 pytest-warnings in 0.15 seconds ================================================================================================
```

**Comment by winkidney** [comment]
@volans- After this issue resolved, the package for "pysmart.smartx" will be update:)

**Comment by volans-** [comment]
@winkidney #5 submitted, thanks for pointing it out, test were passing on Mac OS due to not overriding the staphy function in that test.

**Pull request merged**
